pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
        maven { url = "https://maven.aliyun.com/repository/gradle-plugin" }
        maven { url = "https://maven.aliyun.com/repository/public" }
    }
}

plugins {
    id "org.gradle.toolchains.foojay-resolver-convention" version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = uri("$rootDir/third_party/maven") }
        mavenCentral()
        google()
        maven { url = "https://maven.aliyun.com/repository/public" }
        maven { url = "https://maven.aliyun.com/repository/google" }
        flatDir { dirs "$rootDir/app/libs" }
        maven { url = "https://jitpack.io" }
    }
}

include ':app'
include ':catvod'
include ':chaquo'
include ':nodejs'
include ':quickjs'
rootProject.name = "TV"
